---
-
  hosts: all

  tasks:
    - name: Print Hello
      debug:
        msg: "Login successful!"

    - name: delete log files
      register: grep_output
      shell: "rm /home/vunet/shirish/logs/log*"
    - debug:
        var: grep_output.stdout_lines
