---
- name: command line arguments demo
  hosts: all
  vars:
    file_name: "file-name"
    file_name2: "file-name"
  tasks:
    - name: 'print message'
      shell: stat {{file_name|quote }} && echo success || echo fail
      register: task1
    - debug:
        var: task1.stdout_lines
    - name: 'create file from args'
      shell: touch {{file_name2|quote }} && echo success || echo fail
      register: task2
    - debug:
        var: task2.stdout_lines
      #ansible.builtin.debug:
      #  msg: "fruit is {{ file_name }}"
