---
- name: command line arguments demo
  hosts: all
  vars:
    file_name1: "file-name"
  tasks:
    - name: fill-disk
      shell: "date"
      register:  grep_output
    - debug:
        var: grep_output.stdout_lines
    - name: fill-disk
      shell: "bash /data2/fill-disk.bash"
      register:  command_output
    - debug:
        var: command_output.stdout_lines
