---
- name: command line arguments demo
  hosts: all
  vars:
    file_name1: "file-name"
  tasks:
    - name: error-to-steady-state-switch-over
      shell: "date"
      register:  grep_output
    - debug:
        var: grep_output.stdout_lines
    - name: error-to-steady-state-switch-over
      shell: "bash /home/vunet/datagen/auto-remediation/ibmb-kill-error-start-steady.sh"
      register:  command_output
    - debug:
        var: command_output.stdout_lines
